repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: ^config/.*\.(yml|yaml)$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        name: clang-format (check, v18) [esphome]
        files: ^components/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
        args: ["--dry-run", "--Werror", "--style=file"]