packages:
  base_image: !include satellite1.yaml
  mmwave_ld2450: !include common/mmwave_ld2450.yaml

esphome:
  name: ${node_name}
  project:
    name: ${company_name}.${project_name}
    version: ${esp32_fw_version}+ld2450
