packages:
  base_image: !include satellite1.yaml
  mmwave_ld2450: !include common/mmwave_ld2450.yaml

esphome:
  name: ${node_name}
  project:
    name: ${company_name}.${project_name}
    version: ${esp32_fw_version}+ld2450

# Dashboard import enables automatic updates from GitHub
dashboard_import:
  package_import_url: github://remcom/Satellite1-ESPHome/config/satellite1-dashboard.yaml@main
  import_full_config: false

update:
  - platform: http_request
    name: None
    id: !extend update_http_request
    source: https://github.com/remcom/Satellite1-ESPHome/releases/download/latest/satellite1.ld2450-manifest.json

switch:
  - platform: template
    id: !extend beta_firmware
    name: Beta firmware
    icon: "mdi:test-tube"
    entity_category: diagnostic
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Beta firmware"
      - lambda: id(update_http_request).set_source_url("https://github.com/remcom/Satellite1-ESPHome/releases/download/beta/satellite1.ld2450-manifest.json");
      - component.update: update_http_request
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      - lambda: id(update_http_request).set_source_url("https://github.com/remcom/Satellite1-ESPHome/releases/download/latest/satellite1.ld2450-manifest.json");
      - component.update: update_http_request
