wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: True
  enable_rrm: True
  min_auth_mode: WPA2

network:
  enable_ipv6: true

  ap:
    ssid: "${node_name}"
    password: !secret wifi_ap_password
